/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto;

import java.awt.BorderLayout;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Amanda
 */
public class HomeView extends javax.swing.JFrame {

    HomeController controle = new HomeController();
    DefaultListModel ambList = new DefaultListModel();
    DefaultListModel dispList = new DefaultListModel();
    DefaultListModel userList = new DefaultListModel();

    //add a lista
    private void addArgumentToList(String argument, DefaultListModel listModel, JList list) {
        list.setModel(listModel);
        listModel.addElement(argument);
    }

    //envia as informações de usuario para a tela de bate papo
    public String[] exibirListaNaTela() {
        String elementos = controle.listUserAmbChat(usuarioList.getSelectedValue());
        return elementos.split(", ");
    }
    
    public String usuarioConectade(){
        String usuarioConectade = usuarioList.getSelectedValue();
        return usuarioConectade;
    }

    public JList<String> getUsuarioList() {
        return usuarioList;
    }
   
    /**
     * Creates new form tela
     */
    public HomeView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ambienteButton = new javax.swing.JButton();
        dispositivoButton = new javax.swing.JButton();
        usuarioButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ambienteList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        dispositivoList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        usuarioList = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        jPanel1.setBackground(new java.awt.Color(80, 58, 36));

        ambienteButton.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        ambienteButton.setText("Ambiente");
        ambienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ambienteButtonActionPerformed(evt);
            }
        });

        dispositivoButton.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        dispositivoButton.setText("Quadros (disp)");
        dispositivoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispositivoButtonActionPerformed(evt);
            }
        });

        usuarioButton.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        usuarioButton.setText("Visitante (User)");
        usuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioButtonActionPerformed(evt);
            }
        });

        ambienteList.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        ambienteList.setSelectionForeground(new java.awt.Color(255, 255, 255));
        ambienteList.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ambienteListAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        ambienteList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ambienteListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ambienteList);

        dispositivoList.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        dispositivoList.setSelectionForeground(new java.awt.Color(255, 255, 255));
        dispositivoList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dispositivoListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(dispositivoList);

        usuarioList.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        usuarioList.setSelectionForeground(new java.awt.Color(255, 255, 255));
        usuarioList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usuarioListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(usuarioList);

        jLabel3.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Museu Da Amanda");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ambienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dispositivoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usuarioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(ambienteButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dispositivoButton)
                    .addComponent(usuarioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ambienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ambienteButtonActionPerformed
        addArgumentToList(controle.createAmb(), ambList, ambienteList);
    }//GEN-LAST:event_ambienteButtonActionPerformed

    private void dispositivoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dispositivoButtonActionPerformed
        //Cria um novo dispositivo
        addArgumentToList(controle.createDisp(), dispList, dispositivoList);
    }//GEN-LAST:event_dispositivoButtonActionPerformed

    private void ambienteListAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ambienteListAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_ambienteListAncestorAdded

    private void dispositivoListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dispositivoListMouseClicked
        // Crie um JTextField
        JTextField txtAmb = new JTextField("amb");

        // Crie um painel personalizado contendo a mensagem, o JTextField e os botões
        Object[] opcoes = {"Excluir Dispositivo", "Mover Dispositivo", "Cancelar"};
        JPanel panel = new JPanel(new BorderLayout());
        panel.add(new JLabel("Escolha um ambiente:"), BorderLayout.NORTH);
        panel.add(txtAmb, BorderLayout.CENTER);

        // Mostre a caixa de diálogo
        int escolha = JOptionPane.showOptionDialog(null, panel, "Informações do " + dispositivoList.getSelectedValue(), JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, opcoes, opcoes[0]);

        //Trata a opção que o usuario escolheu
        if (escolha == 0) {
            controle.deleteDisp(dispositivoList.getSelectedValue());
            //atualizar a lista
            int index = dispositivoList.getSelectedIndex();
            dispList.removeElementAt(index);
        } else if (escolha == 1) {
            controle.moveDisp(dispositivoList.getSelectedValue(), txtAmb.getText());
        } else if (escolha == 2) {

        }

    }//GEN-LAST:event_dispositivoListMouseClicked

    private void ambienteListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ambienteListMouseClicked
        // Crie um painel personalizado contendo a mensagem e os botões
        Object[] opcoes = {"Excluir Ambiente", "Cancelar"};

        // Mostre a caixa de diálogo
        int escolha = JOptionPane.showOptionDialog(null, controle.listDisp(ambienteList.getSelectedValue()) + controle.listUser(ambienteList.getSelectedValue()), "Informações do " + ambienteList.getSelectedValue(), JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, opcoes, opcoes[0]);

        //Trata a opção que o usuario escolheu
        if (escolha == 0) {

            if (controle.countDisp(ambienteList.getSelectedValue()) == 0) {
                controle.deleteAmb(ambienteList.getSelectedValue());

                //atualizar a lista
                int index = ambienteList.getSelectedIndex();
                ambList.removeElementAt(index);
            } else {
                //Warning
                JLabel lblMessage = new JLabel("Antes de destruir o ambiente, remova todos os dispositivos e usuários.");
                Object[] texts = {lblMessage};
                JOptionPane.showMessageDialog(null, texts);
            }

        }

    }//GEN-LAST:event_ambienteListMouseClicked

    private void usuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioButtonActionPerformed
        //Cria um novo usuario
        addArgumentToList(controle.createUser(), userList, usuarioList);
        //System.out.println(exibirListaNaTela());
    }//GEN-LAST:event_usuarioButtonActionPerformed

    private void usuarioListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioListMouseClicked
        // Crie um JTextField
        JTextField txtAmb1 = new JTextField("amb");

        // Crie um painel personalizado contendo a mensagem, o JTextField e os botões
        Object[] opcoes = {"Excluir Usuário", "Mover Usuário", "Iniciar Bate Papo", "Cancelar"};
        JPanel panel = new JPanel(new BorderLayout());
        panel.add(new JLabel("Escolha um ambiente:"), BorderLayout.NORTH);
        panel.add(txtAmb1, BorderLayout.CENTER);

        // Mostre a caixa de diálogo
        int escolha = JOptionPane.showOptionDialog(null, panel, "Informações do " + usuarioList.getSelectedValue(), JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, opcoes, opcoes[0]);

        //Trata a opção que o usuario escolheu
        if (escolha == 0) {
            controle.deleteDisp(dispositivoList.getSelectedValue());
            //atualizar a lista
            int index = usuarioList.getSelectedIndex();
            userList.removeElementAt(index);
        } else if (escolha == 1) {
            controle.moveUser(usuarioList.getSelectedValue(), txtAmb1.getText());
        } else if (escolha == 2) {
            ChatView novoBatePapo = new ChatView();
            novoBatePapo.setUsuarioConectade(usuarioList.getSelectedValue());
            novoBatePapo.setAmbNome(controle.findAmbUserChat(usuarioList.getSelectedValue()));
            
            novoBatePapo.setVisible(true);
        } else if (escolha == 3) {

        }
    }//GEN-LAST:event_usuarioListMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ambienteButton;
    private javax.swing.JList<String> ambienteList;
    private javax.swing.JButton dispositivoButton;
    private javax.swing.JList<String> dispositivoList;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton usuarioButton;
    private javax.swing.JList<String> usuarioList;
    // End of variables declaration//GEN-END:variables
}
